gcc -Wall -Werror -Wextra -c main.c
gcc -o main main.o -L../../ -lft
echo "El numero 0..."
./main "0"
echo "El numero 4..."
./main "4"
echo "El numero 34..."
./main "34"
echo "El numero 76..."
./main "76"
echo "El numero 43..."
./main "43"
echo "El numero 98..."
./main "98"
echo "El numero 123..."
./main "123"
echo "El numero 143..."
./main "143"
echo "test"
./main "56" "isascii"
